<?php

namespace Bermuda\MiddlewareFactory\Adapter;

use Bermuda\MiddlewareFactory\Resolver\RequestHandlerParameter;
use Bermuda\MiddlewareFactory\Resolver\RequestParameter;
use Bermuda\MiddlewareFactory\Resolver\RequestParameterKey;
use Bermuda\DI\CallableInvokerInterface;
use Psr\Container\ContainerInterface;
use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Bermuda\MiddlewareFactory\Resolver\RequestAttributeResolver;
use Bermuda\ParameterResolver\ParameterResolver;
use Bermuda\ParameterResolver\ParameterResolverInterface;

/**
 * The CallableAdapter class adapts a user-defined callable
 * so that it conforms to the PSR-15 middleware interface.
 *
 * It uses a callable invoker to resolve any dependencies and invoke
 * the callable. The adapter then normalizes the callable output into
 * a valid ResponseInterface by delegating to either a middleware or
 * request handler, as needed.
 *
 * @internal This class is intended for internal use only.
 */
class CallableAdapter implements MiddlewareInterface
{
    protected $callable;

    public function __construct(
        callable $callable,
        protected readonly CallableInvokerInterface $invoker,
    ) {
        $this->callable = $callable;
    }

    /**
     * Processes an incoming server request and returns a response.
     *
     * This method delegates the processing of the request to a callable via the invoker. The callable's
     * output is evaluated as follows:
     *
     * - If the output implements MiddlewareInterface, the process() method is invoked on it.
     * - If the output implements RequestHandlerInterface, the handle() method is called on it.
     * - Otherwise, if the output is not an instance of ResponseInterface, an UnexpectedValueException is thrown.
     *
     * This ensures that the final result of the callable middleware always conforms to a ResponseInterface.
     *
     * @param ServerRequestInterface  $request The current server request.
     * @param RequestHandlerInterface $handler The request handler to use for further processing if needed.
     *
     * @return ResponseInterface The HTTP response generated by the callable middleware.
     *
     * @throws \dicontainer\CallableInvokerExceptionInterface If there is an error invoking the callable.
     * @throws \UnexpectedValueException If the callable fails to produce a valid response.
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $result = $this->invoker->call($this->callable, $this->provideParams($request, $handler));
        
        if ($result instanceof MiddlewareInterface) return $result->process($request, $handler);
        if ($result instanceof RequestHandlerInterface) return $result->handle($request);

        if (!$result instanceof ResponseInterface) {
            throw new \UnexpectedValueException('Сallable middleware failed to produce a response.');
        }

        return $result;
    }

    /**
     * Provides parameters for invoking the callable middleware.
     *
     * This method builds an array of parameters based on the
     * given server request and request handler. The parameters
     * are resolved using the RequestParameter and RequestHandlerParameter resolvers.
     *
     * @param ServerRequestInterface  $request The current server request.
     * @param RequestHandlerInterface $handler The request handler.
     *
     * @return array An array of parameters to be passed to the callable.
     */
    protected function provideParams(ServerRequestInterface $request, RequestHandlerInterface $handler): array
    {
        return RequestHandlerParameter::set(
            RequestParameter::set([], $request), $handler
        );
    }

    /**
     * Factory method to create single-pass middleware from a callable.
     *
     * Single-pass middleware expects a callable that accepts the server request
     * and a callback which, when invoked, produces a response.
     *
     * @param callable $callable The user-defined middleware callable.
     * @param CallableInvokerInterface $invoker  The invoker to execute the callable.
     *
     * @return CallableAdapter A new instance of CallableAdapter configured for single-pass middleware.
     */
    public static function singlePassMiddleware(
        callable $callable,
        CallableInvokerInterface $invoker,
    ): CallableAdapter
    {
        return new class($callable, $invoker) extends CallableAdapter
        {
            /**
             * Provides parameters specifically suited for single-pass middleware.
             *
             * The parameter list includes:
             * - The server request.
             * - A callback that passes the request to the next request handler.
             *
             * @param ServerRequestInterface  $request The current server request.
             * @param RequestHandlerInterface $handler The request handler to call.
             *
             * @return array An array of parameters for the callable.
             */
            protected function provideParams(ServerRequestInterface $request, RequestHandlerInterface $handler): array
            {
                return RequestParameter::set([$request, static fn (ServerRequestInterface $request): ResponseInterface => $handler->handle($request)], $request);
            }
        };
    }

    /**
     * Factory method to create double-pass middleware from a callable.
     *
     * Double-pass middleware expects a callable that receives the server request,
     * an initial response instance, and a callback that continues request processing.
     *
     * @param callable                 $callable The middleware callable.
     * @param CallableInvokerInterface $invoker  The invoker to execute the callable.
     * @param ResponseFactoryInterface $factory  The response factory used for creating response instances.
     *
     * @return CallableAdapter A new instance of CallableAdapter configured for double-pass middleware.
     */
    public static function doublePassMiddleware(
        callable $callable,
        CallableInvokerInterface $invoker,
        ResponseFactoryInterface $factory
    ): CallableAdapter
    {
        return new class($callable, $invoker, $factory) extends CallableAdapter
        {
            public function __construct(
                callable $callable,
                CallableInvokerInterface $invoker,
                private readonly ResponseFactoryInterface $responseFactory
            ) {
                parent::__construct($callable, $invoker);
            }
            /**
             * Provides parameters specifically suited for double-pass middleware.
             *
             * The parameter list includes:
             * - The server request.
             * - An initial response instance from the response factory.
             * - A callback that passes the server request to the next handler.
             *
             * @param ServerRequestInterface  $request The current server request.
             * @param RequestHandlerInterface $handler The request handler to invoke.
             *
             * @return array An array of parameters for the callable.
             */
            protected function provideParams(ServerRequestInterface $request, RequestHandlerInterface $handler): array
            {
                return RequestParameter::set([$request, $this->responseFactory->createResponse(), static fn (ServerRequestInterface $request): ResponseInterface => $handler->handle($request)], $request);
            }
        };
    }
}
