<?php

namespace Bermuda\MiddlewareFactory\Adapter;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

/**
 * Adapter that converts PSR-15 RequestHandlers into PSR-15 Middleware.
 *
 * This adapter enables RequestHandlerInterface instances to be used seamlessly
 * within middleware pipelines by wrapping them with the MiddlewareInterface.
 * It implements both interfaces, allowing it to function as either a middleware
 * or a final request handler depending on the context.
 *
 * The adapter provides a crucial bridge between different PSR-15 component types:
 * - Allows request handlers to participate in middleware chains
 * - Enables reuse of existing request handlers as middleware components
 * - Maintains the PSR-15 specification compliance
 * - Preserves the original handler's functionality and behavior
 *
 * Key features:
 * - Dual interface implementation (Middleware + RequestHandler)
 * - Fallback handler injection via request attributes
 * - Transparent request/response handling
 * - Zero-overhead wrapper with minimal abstraction
 *
 * The fallback handler mechanism allows wrapped handlers to access the next
 * handler in the pipeline through request attributes, enabling advanced
 * scenarios like conditional delegation or middleware composition.
 *
 * @example Basic usage in middleware factory
 * ```php
 * $factory = new MiddlewareFactory($container);
 * $middleware = $factory->makeMiddleware($requestHandler);
 * // RequestHandler is automatically wrapped in RequestHandlerAdapter
 * ```
 *
 * @example Manual adapter creation
 * ```php
 * $adapter = new RequestHandlerAdapter($myRequestHandler);
 * $response = $adapter->process($request, $nextHandler);
 * // or
 * $response = $adapter->handle($request);
 * ```
 */
final class RequestHandlerAdapter implements MiddlewareInterface, RequestHandlerInterface
{
    /**
     * Request attribute key for storing the fallback handler.
     *
     * This constant defines the attribute key used to inject the next handler
     * in the middleware pipeline into the request object. The wrapped handler
     * can access this fallback handler if needed for conditional processing
     * or advanced middleware patterns.
     *
     * The key uses a fully-qualified namespace to avoid conflicts with
     * application-specific attributes and provides clear identification
     * of the adapter's internal functionality.
     */
    public const string FALLBACK_HANDLER_ATTRIBUTES_KEY = "Bermuda\MiddlewareFactory\Adapter:fallback";

    /**
     * Creates a new request handler adapter.
     *
     * @param RequestHandlerInterface $handler The request handler to wrap.
     *                                         This handler will be called for both
     *                                         middleware processing and direct handling.
     */
    public function __construct(
        private readonly RequestHandlerInterface $handler,
    ) {
    }

    /**
     * Processes a server request as middleware by delegating to the wrapped handler.
     *
     * This method implements the MiddlewareInterface by:
     * 1. Injecting the fallback handler into the request attributes
     * 2. Delegating request processing to the wrapped handler
     * 3. Returning the handler's response directly
     *
     * The fallback handler injection allows the wrapped handler to access
     * the next handler in the pipeline through request attributes if needed.
     * This enables advanced scenarios where the handler needs to conditionally
     * delegate to the next middleware in the chain.
     *
     * @param ServerRequestInterface $request The server request to process
     * @param RequestHandlerInterface $handler The next handler in the middleware pipeline
     * @return ResponseInterface The response generated by the wrapped handler
     *
     * @example Handler accessing fallback
     * ```php
     * class ConditionalHandler implements RequestHandlerInterface
     * {
     *     public function handle(ServerRequestInterface $request): ResponseInterface
     *     {
     *         if ($this->shouldDelegate($request)) {
     *             $fallback = $request->getAttribute(RequestHandlerAdapter::FALLBACK_HANDLER_ATTRIBUTES_KEY);
     *             return $fallback->handle($request);
     *         }
     *         return $this->generateResponse($request);
     *     }
     * }
     * ```
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        return $this->handler->handle(
            $request->withAttribute(self::FALLBACK_HANDLER_ATTRIBUTES_KEY, $handler)
        );
    }

    /**
     * Handles a server request directly by delegating to the wrapped handler.
     *
     * This method implements the RequestHandlerInterface by directly
     * delegating to the wrapped handler without any modifications.
     * It enables the adapter to function as a standalone request handler
     * when not used within a middleware pipeline.
     *
     * No fallback handler is injected in this case since there is no
     * middleware pipeline context to provide one.
     *
     * @param ServerRequestInterface $request The server request to handle
     * @return ResponseInterface The response generated by the wrapped handler
     *
     * @example Direct handler usage
     * ```php
     * $adapter = new RequestHandlerAdapter($handler);
     * $response = $adapter->handle($request);
     * // Equivalent to: $handler->handle($request)
     * ```
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->handler->handle($request);
    }
}